### ISSUE TITLE
questions about visualization for attention

### ISSUE THREAD

**Issue by xixiareone** [szzexpoi/AiR#4]
Thanks your greatful work. I am interested in your work. Could you please provide codes about heamap on region?
Many thanks

**Comment by szzexpoi** [comment]
Hi xixiareone,

Thanks for your interest in our work. There are many ways to visualize an attention map. The specific method we used is to overlay the image with the attention map:

```
from matplotlib import pyplot as plt
import cv2
import numpy as np

def overlay_heatmap(img,att,cmap=plt.cm.jet):
    gamma = 1.0
    att = cv2.blur(att,(35,35))
    colorized = cmap(np.uint8(att*255))
    alpha = 0.7
    overlaid = np.uint8(img*(1-alpha)+colorized[:,:,2::-1]*255*alpha)
    return overlaid
```

Note that the input images and visualization outputs are in the BGR color space.
